<?php
/**
 * tests/dev-router.php — the router script for the PHP built-in server.
 *
 *   php -S 127.0.0.1:8899 -t . tests/dev-router.php
 *
 *  Why this file exists (25 Sep 2026). Without a router script the built-in
 *  server decides for itself whether a URI is "a static file" or "something
 *  for index.php", and it decides on a dot: a path whose last segment
 *  contains one is treated as a file, and when that file is missing the
 *  server answers with its own 404 page instead of walking up to index.php.
 *  That is what turned three route-page checks red in CI — the two dynamic
 *  sitemaps are generated by index.php (RoutePages::sitemapRoutes /
 *  sitemapPages) and exist nowhere on disk, exactly as nginx serves them in
 *  production:
 *
 *      location / { try_files $uri $uri/ /index.php?$query_string; }
 *
 *  This router states that same rule explicitly, so the dev server behaves
 *  like production on every PHP version:
 *
 *    · an existing file that is not PHP  → the server serves it (return false),
 *      so CSS, JS, images, robots.txt and the static sitemap.xml keep their
 *      own MIME types and Range handling;
 *    · an existing .php file anywhere    → run it, with SCRIPT_NAME,
 *      SCRIPT_FILENAME and PHP_SELF set as PHP-FPM would (admin/, api/,
 *      cron/ and pay-share.php all depend on these);
 *    · a directory holding index.php     → run that;
 *    · anything else                     → index.php, REQUEST_URI untouched,
 *      which is what the route pages, the sitemaps and the SPA need.
 *
 *  Test infrastructure only: nothing here ships to the server. Production
 *  is nginx + PHP-FPM and never loads this file.
 */

declare(strict_types=1);

$root = realpath(__DIR__ . '/..');
if ($root === false) {
    http_response_code(500);
    exit('dev-router: cannot resolve the document root');
}

$uri  = (string) ($_SERVER['REQUEST_URI'] ?? '/');
$path = (string) (parse_url($uri, PHP_URL_PATH) ?: '/');
$path = rawurldecode($path);

/* A path is only ever looked up inside the document root: realpath() first,
   then a prefix test, so "/../config/config.php" cannot escape. */
$candidate = $root . '/' . ltrim($path, '/');
$real      = realpath($candidate);
$inside    = $real !== false && ($real === $root || str_starts_with($real, $root . DIRECTORY_SEPARATOR));

/* Production is nginx, and nginx refuses a whole list of paths outright
   (deploy/nginx-shreehariglobal.in.conf). The dev server must refuse them
   too: a test that quietly passes here because it could read
   /includes/db.php or /app.template.html would be testing a site that does
   not exist. The one exception nginx itself makes is /tests/preflight.php,
   the post-deploy check the operator runs from a browser. */
$blocked = static function (string $p): bool {
    if ($p === '/tests/preflight.php') {
        return false;
    }
    if (preg_match('#^/(config|includes|database|backup|logs|cron|invoice|tickets|tests)/#', $p) === 1) {
        return true;
    }
    if ($p === '/app.template.html' || $p === '/install.php') {
        return true;
    }
    if (preg_match('#/\.#', $p) === 1) {                       // dotfiles: /.git/, /.env
        return true;
    }
    if (preg_match('#\.(bak|sql|log|ini|sample|dist|md)$#i', $p) === 1) {
        return true;
    }
    if (preg_match('#^/uploads/(challan|chalani|agents-kyc|passengers)/#', $p) === 1) {
        return true;
    }
    return preg_match('#^/uploads/.*\.php$#i', $p) === 1;
};
if ($blocked($path)) {
    http_response_code(404);
    header('Content-Type: text/plain; charset=utf-8');
    echo "404 — nginx refuses this path in production (deploy/nginx-shreehariglobal.in.conf), so the dev server does too.\n";
    return;
}

$serve = static function (string $file, string $scriptName) use ($root): void {
    $_SERVER['SCRIPT_FILENAME'] = $file;
    $_SERVER['SCRIPT_NAME']     = $scriptName;
    $_SERVER['PHP_SELF']        = $scriptName;
    $_SERVER['DOCUMENT_ROOT']   = $root;
    require $file;
};

if ($inside && is_file($real)) {
    if (str_ends_with(strtolower($real), '.php')) {
        // Never `return false` for a PHP file: that would hand the source
        // code to the browser instead of running it.
        $serve($real, $path);
        return;
    }
    return false;   // the built-in server sends the file itself
}

if ($inside && is_dir($real) && is_file($real . '/index.php')) {
    $serve($real . '/index.php', rtrim($path, '/') . '/index.php');
    return;
}

$serve($root . '/index.php', '/index.php');
