<?php
/**
 * includes/challanpng.php — the per-bus, per-date CHALLAN as one PNG image.
 *
 * SHG AI BRAIN master prompt, Phase 1.5 (10 Sep 2026). The office already had
 * three passenger sheets for a departure — the HTML manifest, the Nepali
 * chalani PDF (ChalaniPdf) and the English ReportPdf — but every one of them
 * is a TABLE. What the driver, the border desk and the owner's WhatsApp group
 * actually pass around is a PICTURE of the coach: both floors, every berth,
 * who sits on it, where they board, and the totals. That did not exist.
 *
 * What this renders (English only — the challan is for customs/officials):
 *   · header: company, bus number/name, route, date, departure, driver,
 *     challan number (same CH-YYYYMMDD-ROUTECODE the chalani PDF uses)
 *   · both decks of the coach in the PHYSICAL (sharing) namespace — the one
 *     inventory every sale really occupies. A private cabin is drawn as ONE
 *     merged gold cell over the two beds it takes (Seats::physicalSeats), so
 *     the picture agrees with the seat map and the sale gate, never with a
 *     label that belongs to a different bed.
 *   · per berth: passenger name(s), mobile, pickup -> drop short codes, PNR,
 *     payment state; empty berths blank; blocked / staff / held marked.
 *   · totals: sold, empty, held, out of service, sharing vs private, passengers,
 *     revenue (confirmed) and amount still pending.
 *   · footer: "Generated by SHG AI Brain | ShreeHariGlobal.in".
 *
 * Freshness without a queue: render() fingerprints the DATA (every sold berth,
 * hold, block, gender lock, bus, driver, departure) and only re-renders when
 * the fingerprint moved. So the file is regenerated "on every booking change"
 * exactly as the prompt asks, but lazily, on the next open — nothing runs on
 * the sale path, nothing can slow a checkout, and a missed event can never
 * leave a stale picture behind (RULE 09: self-correcting). Every render is
 * logged to challan_reports (database/upgrade-2026-09-challan-png.sql).
 *
 * HEADINGS ROMAN, NAMES AS TYPED. The labels and column heads stay English —
 * this is the crew and border-desk copy. A PASSENGER NAME prints in the script
 * it was written in: GD does form the Devanagari conjuncts, and dev_shape()
 * supplies the one reordering step it misses. Until 11 Sep 2026 a Nepali name
 * printed as the literal words "(Nepali name)", which left the crew a berth
 * they could not match to a person.
 *
 * Reads only. Writes one PNG under UPLOAD_PATH/challan/<date>/ and one
 * challan_reports row. Never touches a booking, a seat or a fare.
 */
declare(strict_types=1);

final class ChallanPng
{
    /** Print-quality width (the prompt asks for >= 1200 px). */
    public const WIDTH = 1600;

    /** Bump whenever the drawing changes so every cached challan re-renders once. */
    public const LAYOUT_VERSION = 5;   // 5 = berths print the LA1/UA1 row-letter grid id

    private const MARGIN = 56;
    private const CELL_H = 118;
    private const ROW_GAP = 10;
    private const AISLE_W = 36;
    private const CELL_GAP = 8;

    /* ------------------------------------------------------------------ */
    /*  Data                                                               */
    /* ------------------------------------------------------------------ */

    /** Schedule + route + bus + driver for the header. Null when unknown. */
    public static function schedule(int $scheduleId): ?array
    {
        return Database::fetch(
            "SELECT s.id, s.travel_date, s.status, s.slot, s.route_id, s.bus_id, s.is_blocked,
                    s.coach_type_override,
                    COALESCE(s.dep_time_override, r.dep_time) AS dep_time,
                    r.route_code, r.from_city, r.to_city, r.coach_type,
                    bu.bus_number, bu.bus_name,
                    d.full_name AS driver_name, d.phone AS driver_phone
               FROM schedules s
               JOIN routes r ON r.id = s.route_id
               LEFT JOIN buses bu ON bu.id = COALESCE(s.bus_id, r.bus_id)
               LEFT JOIN drivers d ON d.id = s.driver_id
              WHERE s.id = :id",
            ['id' => $scheduleId]
        );
    }

    /**
     * Everything the picture needs, plus the fingerprint that decides whether
     * the cached file is still the truth.
     *
     * @return array{coach:string, layout:array, beds:array<string,array>, totals:array, unitLocks:array, fingerprint:string}
     */
    public static function collect(int $scheduleId, array $sched): array
    {
        $coach  = Seats::effectiveCoach($sched, ['coach_type' => (string) ($sched['coach_type'] ?? 'sleeper')]);
        $layout = Seats::layoutFor($coach, 'sharing');
        $allBeds = Seats::seatIds($coach, 'sharing');

        $rows = Database::fetchAll(
            "SELECT bs.seat_no, b.id AS booking_id, b.booking_mode, b.pnr, b.status, b.source, b.is_cod,
                    b.contact_phone, b.total_amount,
                    bp.id AS pax_id, bp.full_name, bp.gender,
                    bl.boarding_stop, bl.drop_stop
               FROM booking_seats bs
               JOIN bookings b ON b.id = bs.booking_id
               LEFT JOIN booking_legs bl ON bl.id = bs.leg_id
               LEFT JOIN booking_passengers bp ON bp.booking_id = bs.booking_id AND bp.seat_no = bs.seat_no
              WHERE bs.schedule_id = :s AND bs.released_at IS NULL
              ORDER BY LENGTH(bs.seat_no), bs.seat_no, bp.id",
            ['s' => $scheduleId]
        );

        /* One sale per booking_seats row (a private cabin is ONE row over two
           beds); passengers on that row are collected, not overwritten. */
        $sales = [];
        $paxHere = [];
        foreach ($rows as $r) {
            $seat = (string) $r['seat_no'];
            if (!isset($sales[$seat])) {
                $sales[$seat] = [
                    'seat'       => $seat,
                    'mode'       => (string) ($r['booking_mode'] ?? 'sharing') === 'private' ? 'private' : 'sharing',
                    'booking_id' => (int) $r['booking_id'],
                    'pnr'        => (string) $r['pnr'],
                    'status'     => (string) $r['status'],
                    'source'     => (string) ($r['source'] ?? ''),
                    'is_cod'     => (int) ($r['is_cod'] ?? 0) === 1,
                    'phone'      => (string) ($r['contact_phone'] ?? ''),
                    'amount'     => (float) ($r['total_amount'] ?? 0),
                    'board'      => (string) ($r['boarding_stop'] ?? ''),
                    'drop'       => (string) ($r['drop_stop'] ?? ''),
                    'names'      => [],
                    'genders'    => [],
                ];
            }
            if (!empty($r['pax_id'])) {
                $sales[$seat]['names'][]   = (string) ($r['full_name'] ?? '');
                $sales[$seat]['genders'][] = (string) ($r['gender'] ?? '');
                $bid = (int) $r['booking_id'];
                $paxHere[$bid] = ($paxHere[$bid] ?? 0) + 1;
            }
        }

        /* Revenue share: total_amount covers the WHOLE booking (a round trip's
           return leg included), so a booking's money is pro-rated by the
           passengers it has on THIS departure — the manifest's own rule. */
        $paxAll = [];
        if ($paxHere !== []) {
            $in = implode(',', array_map('intval', array_keys($paxHere)));
            foreach (Database::fetchAll("SELECT booking_id, COUNT(*) c FROM booking_passengers WHERE booking_id IN ($in) GROUP BY booking_id") as $pr) {
                $paxAll[(int) $pr['booking_id']] = (int) $pr['c'];
            }
        }

        $holds = [];
        foreach (Database::fetchAll(
            'SELECT seat_no FROM seat_locks WHERE schedule_id = :s AND expires_at > NOW()',
            ['s' => $scheduleId]
        ) as $h) {
            $holds[(string) $h['seat_no']] = true;
        }
        $blocked = array_flip(Seats::blockedSeats($scheduleId));
        $staff   = array_flip(Seats::staffSeats($coach));

        $unitLocks = [];
        foreach (Database::fetchAll(
            'SELECT unit_key, gender_lock FROM schedule_unit_locks WHERE schedule_id = :s',
            ['s' => $scheduleId]
        ) as $u) {
            if ((string) $u['gender_lock'] !== 'none') {
                $unitLocks[(string) $u['unit_key']] = (string) $u['gender_lock'];
            }
        }

        /* Expand every sale onto the PHYSICAL beds it occupies. */
        $beds = [];
        foreach ($allBeds as $bed) {
            $beds[$bed] = ['bed' => $bed, 'status' => 'open', 'sale' => null, 'cabin' => null];
        }
        $seenBooking = [];
        $totals = ['beds' => count($allBeds), 'booked' => 0, 'held' => 0, 'blocked' => 0, 'staff' => 0,
                   'sharing' => 0, 'private' => 0, 'passengers' => 0, 'revenue' => 0.0, 'pending' => 0.0];
        foreach ($sales as $sale) {
            $physical = Seats::physicalSeats($sale['seat'], $sale['mode'], $coach);
            foreach ($physical as $bed) {
                if (!isset($beds[$bed])) {
                    continue;
                }
                $beds[$bed]['status'] = 'booked';
                $beds[$bed]['sale']   = $sale;
                $beds[$bed]['cabin']  = $sale['mode'] === 'private' ? $sale['seat'] : null;
                $totals['booked']++;
            }
            if ($sale['mode'] === 'private') {
                $totals['private']++;
            } else {
                $totals['sharing']++;
            }
            $totals['passengers'] += count($sale['names']);
            $bid = $sale['booking_id'];
            if (!isset($seenBooking[$bid])) {
                $seenBooking[$bid] = true;
                $here  = $paxHere[$bid] ?? 0;
                $all   = $paxAll[$bid] ?? 0;
                $share = ($here > 0 && $all > 0) ? $sale['amount'] * ($here / $all) : $sale['amount'];
                if (in_array($sale['status'], ['confirmed', 'completed'], true)) {
                    $totals['revenue'] += $share;
                } else {
                    $totals['pending'] += $share;
                }
            }
        }
        foreach ($beds as $bed => &$b) {
            if ($b['status'] !== 'open') {
                continue;
            }
            if (isset($blocked[$bed]))    { $b['status'] = 'blocked'; $totals['blocked']++; }
            elseif (isset($staff[$bed]))  { $b['status'] = 'staff';   $totals['staff']++; }
            elseif (isset($holds[$bed]))  { $b['status'] = 'held';    $totals['held']++; }
        }
        unset($b);
        $totals['empty'] = max(0, $totals['beds'] - $totals['booked'] - $totals['held'] - $totals['blocked'] - $totals['staff']);

        /* The fingerprint: everything the picture shows. Holds count too —
           a held berth IS a change on the map, and it expires on its own. */
        $fp = md5(json_encode([
            self::LAYOUT_VERSION, $coach,
            array_intersect_key($sched, array_flip(['travel_date', 'dep_time', 'status', 'bus_number', 'bus_name', 'driver_name', 'driver_phone', 'route_code', 'from_city', 'to_city', 'is_blocked'])),
            $sales, array_keys($holds), array_keys($blocked), $unitLocks,
        ], JSON_UNESCAPED_UNICODE));

        return ['coach' => $coach, 'layout' => $layout, 'beds' => $beds, 'totals' => $totals,
                'unitLocks' => $unitLocks, 'fingerprint' => $fp];
    }

    /** Short label for the bus in file names and the log: the plate, else BUS-<route code>. */
    public static function busLabel(array $sched): string
    {
        $plate = strtoupper(trim((string) ($sched['bus_number'] ?? '')));
        $lbl   = $plate !== '' ? $plate : 'BUS-' . strtoupper((string) ($sched['route_code'] ?? 'X'));
        $lbl   = preg_replace('/[^A-Z0-9]+/', '-', $lbl) ?? $lbl;
        return trim($lbl, '-') ?: 'BUS';
    }

    /** Where the file lives: UPLOAD_PATH/challan/YYYY-MM-DD/<BUS>-S<schedule>.png */
    public static function fileFor(array $sched): string
    {
        $date = (string) ($sched['travel_date'] ?? todayISO());
        return rtrim(UPLOAD_PATH, '/\\') . '/challan/' . $date . '/' . self::busLabel($sched) . '-S' . (int) $sched['id'] . '.png';
    }

    /** The newest challan_reports row for a departure, or null (table optional). */
    public static function latest(int $scheduleId): ?array
    {
        try {
            return Database::fetch(
                'SELECT id, file_path, fingerprint, width, height, trigger_event, generated_by, generated_at
                   FROM challan_reports WHERE schedule_id = :s ORDER BY id DESC LIMIT 1',
                ['s' => $scheduleId]
            );
        } catch (Throwable $e) {
            return null;   // migration not applied yet — render still works, just never cached
        }
    }

    /**
     * Render (or reuse) the challan for one departure.
     *
     * @return array{path:string, file:string, fresh:bool, fingerprint:string, width:int, height:int, bus:string}
     */
    public static function render(int $scheduleId, string $trigger = 'manual', ?int $adminId = null, bool $force = false): array
    {
        $sched = self::schedule($scheduleId);
        if ($sched === null) {
            throw new RuntimeException('Unknown departure.');
        }
        $data = self::collect($scheduleId, $sched);
        $path = self::fileFor($sched);
        $last = self::latest($scheduleId);

        if (!$force && $last !== null && (string) $last['fingerprint'] === $data['fingerprint'] && is_file($path)) {
            return ['path' => $path, 'file' => basename($path), 'fresh' => false, 'fingerprint' => $data['fingerprint'],
                    'width' => (int) $last['width'], 'height' => (int) $last['height'], 'bus' => self::busLabel($sched)];
        }

        $dir = dirname($path);
        // ensurePrivateDir leaves the .htaccess guard at the root of the
        // challan tree: this sheet carries passenger names and mobiles, and
        // uploads/ is not in git, so the protection has to be written next
        // to the data rather than installed once. (25 Sep 2026.)
        if (!ensurePrivateDir($dir)) {
            throw new RuntimeException('Cannot create the challan folder.');
        }
        [$w, $h] = self::draw($sched, $data, $path);

        try {
            Database::insert('challan_reports', [
                'schedule_id'   => $scheduleId,
                'bus_label'     => self::busLabel($sched),
                'report_date'   => (string) $sched['travel_date'],
                'file_path'     => 'challan/' . (string) $sched['travel_date'] . '/' . basename($path),
                'fingerprint'   => $data['fingerprint'],
                'width'         => $w,
                'height'        => $h,
                'trigger_event' => substr($trigger, 0, 30),
                'generated_by'  => $adminId,
            ]);
        } catch (Throwable $e) {
            Logger::error('challan_reports insert failed: ' . $e->getMessage());
        }
        Logger::audit('challan.generated', 'schedule', (string) $scheduleId, null,
            ['file' => basename($path), 'trigger' => $trigger, 'booked' => $data['totals']['booked'], 'empty' => $data['totals']['empty']],
            self::busLabel($sched) . ' ' . (string) $sched['travel_date'] . ' (' . $w . 'x' . $h . ')');

        return ['path' => $path, 'file' => basename($path), 'fresh' => true, 'fingerprint' => $data['fingerprint'],
                'width' => $w, 'height' => $h, 'bus' => self::busLabel($sched)];
    }

    /* ------------------------------------------------------------------ */
    /*  Drawing                                                            */
    /* ------------------------------------------------------------------ */

    /** @return array{0:int,1:int} width, height */
    private static function draw(array $sched, array $data, string $path): array
    {
        $layout = $data['layout'];
        $beds   = $data['beds'];
        $tot    = $data['totals'];
        $W      = self::WIDTH;
        $M      = self::MARGIN;

        /* Geometry — cells divide the width the coach has. */
        $maxPerRow = 1;
        foreach ($layout['decks'] as $deck) {
            foreach ($deck['rows'] as $row) {
                $maxPerRow = max($maxPerRow, count($row['left']) + count($row['right']));
            }
        }
        $cellW = (int) floor(($W - 2 * $M - self::AISLE_W - self::CELL_GAP * ($maxPerRow - 1)) / $maxPerRow);
        $cellW = min($cellW, 300);
        $gridW = $cellW * $maxPerRow + self::AISLE_W + self::CELL_GAP * ($maxPerRow - 1);
        $gridX = (int) (($W - $gridW) / 2);

        $deckBlockH = static function (array $deck): int {
            return 52 + count($deck['rows']) * (self::CELL_H + self::ROW_GAP) + 16;
        };
        $H = 150 + 58 + 46;                       // header + meta + legend
        foreach ($layout['decks'] as $deck) {
            $H += $deckBlockH($deck) + 18;
        }
        $H += 128 + 76;                           // totals + two-line footer

        $im = imagecreatetruecolor($W, $H);
        imagealphablending($im, true);
        imageantialias($im, true);
        $c = static fn(string $hex): int => imagecolorallocate($im, (int) hexdec(substr($hex, 1, 2)), (int) hexdec(substr($hex, 3, 2)), (int) hexdec(substr($hex, 5, 2)));
        $white = $c('#FFFFFF'); $ink = $c('#15233B'); $muted = $c('#5B6B85'); $line = $c('#C9D3E2');
        $navy = $c('#0B2A5B'); $navy2 = $c('#12407F'); $orange = $c('#F07C1F');
        $stroke = ['open' => $c('#B8C4D6'), 'booked' => $c('#2E8B57'), 'private' => $c('#C9A227'), 'held' => $c('#E0A800'),
                   'blocked' => $c('#8A94A6'), 'staff' => $c('#2E5FA8'), 'pending' => $c('#D9822B')];
        $fill = ['open' => $white, 'booked' => $c('#DFF5E4'), 'private' => $c('#FFF1C2'), 'held' => $c('#FFF6D6'),
                 'blocked' => $c('#E4E7EC'), 'staff' => $c('#DDEBFF'), 'pending' => $c('#FFE9D6')];
        $pink = $c('#E91E63');
        imagefilledrectangle($im, 0, 0, $W, $H, $white);

        /* ---- header band ---- */
        imagefilledrectangle($im, 0, 0, $W, 150, $navy);
        imagefilledrectangle($im, 0, 150, $W, 156, $orange);
        $x = $M;
        $logo = Ticket::logoFile();
        if ($logo !== null) {
            $li = @(str_ends_with(strtolower($logo), '.png') ? imagecreatefrompng($logo) : imagecreatefromjpeg($logo));
            if ($li !== false) {
                $lh = 84; $lw = (int) round(imagesx($li) * $lh / max(1, imagesy($li)));
                imagecopyresampled($im, $li, $x, 33, 0, 0, $lw, $lh, imagesx($li), imagesy($li));
                imagedestroy($li);
                $x += $lw + 22;
            }
        }
        $company = self::roman(Settings::getString('company_name', APP_NAME)) ?: 'S Hari Global Pvt Ltd';
        self::text($im, 34, $x, 34, $white, $company, true);
        self::text($im, 19, $x, 82, $c('#C7D6F0'), 'BUS CHALLAN  ·  Seat-wise passenger sheet  ·  ' . (string) ($sched['travel_date'] ?? ''));
        self::text($im, 15, $x, 112, $c('#9FB4D8'), 'Challan no. ' . self::challanNo($sched) . '   ·   SHG AI BRAIN');
        $busNo = self::roman((string) ($sched['bus_number'] ?? '')) ?: self::busLabel($sched);
        $bw = self::width(40, $busNo);
        self::text($im, 40, $W - $M - $bw, 30, $white, $busNo, true);
        $busName = self::roman((string) ($sched['bus_name'] ?? ''));
        if ($busName !== '') {
            $nw = self::width(18, $busName);
            self::text($im, 18, $W - $M - $nw, 84, $c('#C7D6F0'), $busName);
        }
        $coachTxt = strtoupper($data['coach']) . ' · ' . $tot['beds'] . ' berths';
        $cw = self::width(15, $coachTxt);
        self::text($im, 15, $W - $M - $cw, 112, $c('#9FB4D8'), $coachTxt);

        /* ---- meta strip ---- */
        $y = 156;
        imagefilledrectangle($im, 0, $y, $W, $y + 58, $c('#F3F6FB'));
        $route = self::roman((string) $sched['from_city']) . ' -> ' . self::roman((string) $sched['to_city']) . ' (' . strtoupper((string) $sched['route_code']) . ')';
        $dep   = (string) ($sched['dep_time'] ?? '');
        $depTs = $dep !== '' ? strtotime((string) $sched['travel_date'] . ' ' . $dep) : false;
        $meta  = 'ROUTE ' . $route . '    DATE ' . formatDate((string) $sched['travel_date'], 'D, j M Y')
               . '    DEPARTURE ' . ($depTs !== false ? date('g:i A', $depTs) : '-');
        $drv = self::roman((string) ($sched['driver_name'] ?? ''));
        if ($drv !== '') {
            $meta .= '    DRIVER ' . $drv . (!empty($sched['driver_phone']) ? ' ' . self::roman((string) $sched['driver_phone']) : '');
        }
        if ((string) ($sched['status'] ?? '') === 'cancelled') {
            $meta .= '    ** TRIP CANCELLED **';
        }
        self::text($im, 18, $M, $y + 16, $ink, self::fit(18, $meta, $W - 2 * $M), true);
        $y += 58;

        /* ---- legend ---- */
        $lx = $M; $ly = $y + 10;
        foreach ([['open', 'Empty'], ['booked', 'Sold (sharing)'], ['private', 'Private cabin'], ['pending', 'Payment pending'],
                  ['held', 'Held (checkout)'], ['blocked', 'Out of service'], ['staff', 'Staff / emergency']] as [$k, $lbl]) {
            self::roundRect($im, $lx, $ly, $lx + 26, $ly + 22, 5, $fill[$k], $stroke[$k]);
            self::text($im, 14, $lx + 34, $ly + 1, $muted, $lbl);
            $lx += 34 + self::width(14, $lbl) + 30;
        }
        $lx += 6;
        imagefilledrectangle($im, $lx, $ly, $lx + 26, $ly + 5, $pink);
        self::text($im, 14, $lx + 34, $ly + 1, $muted, 'Women-only cabin');
        $y += 46;

        /* ---- decks ---- */
        $deckNames = ['L' => 'FIRST FLOOR  ·  LOWER DECK', 'U' => 'SECOND FLOOR  ·  UPPER DECK', 'M' => 'MAIN DECK'];
        foreach ($layout['decks'] as $deck) {
            $key = (string) ($deck['key'] ?? 'L');
            $ids = [];
            foreach ($deck['rows'] as $row) { foreach (array_merge($row['left'], $row['right']) as $s) { $ids[] = $s; } }
            $firstLbl = isset($ids[0]) ? Seats::displayLabel((string) $ids[0], $data['coach'], 'sharing') : '';
            $lastLbl  = isset($ids[count($ids) - 1]) ? Seats::displayLabel((string) $ids[count($ids) - 1], $data['coach'], 'sharing') : '';
            $title = ($deckNames[$key] ?? strtoupper((string) ($deck['label'] ?? 'DECK'))) . '   (' . $firstLbl . ' - ' . $lastLbl . ')';
            imagefilledrectangle($im, $M, $y, $W - $M, $y + 40, $navy2);
            self::text($im, 19, $M + 16, $y + 8, $white, $title, true);
            $deckSold = 0;
            foreach ($ids as $s) { if (($beds[$s]['status'] ?? '') === 'booked') { $deckSold++; } }
            $dr = $deckSold . ' / ' . count($ids) . ' sold';
            self::text($im, 16, $W - $M - 16 - self::width(16, $dr), $y + 10, $c('#C7D6F0'), $dr);
            $y += 52;

            foreach ($deck['rows'] as $row) {
                $cx = $gridX;
                self::drawBlock($im, $row['left'], $beds, $data['unitLocks'], $data['coach'], $cx, $y, $cellW, $fill, $stroke, $ink, $muted, $line, $pink);
                $cx += count($row['left']) * ($cellW + self::CELL_GAP) - self::CELL_GAP;
                /* aisle */
                imagesetstyle($im, [$line, $line, $line, IMG_COLOR_TRANSPARENT, IMG_COLOR_TRANSPARENT]);
                imageline($im, $cx + (int) (self::AISLE_W / 2), $y, $cx + (int) (self::AISLE_W / 2), $y + self::CELL_H, IMG_COLOR_STYLED);
                $cx += self::AISLE_W;
                self::drawBlock($im, $row['right'], $beds, $data['unitLocks'], $data['coach'], $cx, $y, $cellW, $fill, $stroke, $ink, $muted, $line, $pink);
                $y += self::CELL_H + self::ROW_GAP;
            }
            $y += 16 + 18;
        }

        /* ---- totals ---- */
        self::roundRect($im, $M, $y, $W - $M, $y + 118, 14, $c('#F3F6FB'), $line);
        $boxes = [
            ['SOLD', (string) $tot['booked'] . ' / ' . $tot['beds']],
            ['EMPTY', (string) $tot['empty']],
            ['HELD', (string) $tot['held']],
            ['OUT OF SERVICE', (string) ($tot['blocked'] + $tot['staff'])],
            ['SHARING', (string) $tot['sharing'] . ' berth' . ($tot['sharing'] === 1 ? '' : 's')],
            ['PRIVATE', (string) $tot['private'] . ' cabin' . ($tot['private'] === 1 ? '' : 's')],
            ['PASSENGERS', (string) $tot['passengers']],
            ['REVENUE (PAID)', self::rupees($tot['revenue'])],
            ['PENDING', self::rupees($tot['pending'])],
        ];
        /* Money boxes get more room than count boxes so their labels never collide. */
        $weights = [1, 1, 1, 1.15, 1.1, 1.1, 1.05, 1.5, 1.3];
        $unit = ($W - 2 * $M - 44) / array_sum($weights);
        $bx = $M + 22;
        foreach ($boxes as $i => [$lbl, $val]) {
            $bw = (int) ($unit * ($weights[$i] ?? 1));
            self::text($im, 12, $bx, $y + 22, $muted, self::fit(12, $lbl, $bw - 10), true);
            self::text($im, $i >= 7 ? 22 : 28, $bx, $y + 48, $i === 8 && $tot['pending'] > 0 ? $stroke['pending'] : $ink, self::fit($i >= 7 ? 22 : 28, $val, $bw - 12), true);
            $bx += $bw;
        }
        $y += 128;

        /* ---- footer ---- */
        imageline($im, $M, $y + 6, $W - $M, $y + 6, $line);
        $foot = 'Generated by SHG AI Brain | ShreeHariGlobal.in   ·   ' . date('D, j M Y g:i A') . '   ·   ' . self::challanNo($sched);
        self::text($im, 14, $M, $y + 16, $muted, $foot);
        $tag = 'Every berth drawn from the live booking register - the same inventory the seat map sells from.';
        self::text($im, 12, $M, $y + 40, $c('#8A94A6'), $tag);

        /* ---- write atomically ---- */
        $tmp = $path . '.tmp';
        if (!imagepng($im, $tmp, 6)) {
            imagedestroy($im);
            throw new RuntimeException('Could not write the challan PNG.');
        }
        imagedestroy($im);
        if (!@rename($tmp, $path)) {
            @unlink($tmp);
            throw new RuntimeException('Could not place the challan PNG.');
        }
        return [$W, $H];
    }

    /**
     * One block of adjacent beds (the left or right side of a row). Two beds
     * that belong to the SAME private cabin are drawn as one merged cell.
     *
     * @param array<int,string> $ids
     */
    private static function drawBlock($im, array $ids, array $beds, array $unitLocks, string $coach, int $x, int $y, int $cellW,
                                      array $fill, array $stroke, int $ink, int $muted, int $line, int $pink): void
    {
        $n = count($ids);
        for ($i = 0; $i < $n; $i++) {
            $bed  = $ids[$i];
            $info = $beds[$bed] ?? ['bed' => $bed, 'status' => 'open', 'sale' => null, 'cabin' => null];
            $span = 1;
            if ($info['cabin'] !== null && $i + 1 < $n) {
                $next = $beds[$ids[$i + 1]] ?? null;
                if ($next !== null && $next['cabin'] === $info['cabin'] && ($next['sale']['booking_id'] ?? 0) === ($info['sale']['booking_id'] ?? -1)) {
                    $span = 2;
                }
            }
            $w = $cellW * $span + self::CELL_GAP * ($span - 1);
            // Row-letter grid id (LA1, UB3…); this is the physical coach picture,
            // so every bed is named in the canonical sharing namespace.
            $label = $span === 2
                ? Seats::displayLabel((string) $bed, $coach, 'sharing') . ' + ' . Seats::displayLabel((string) $ids[$i + 1], $coach, 'sharing')
                : Seats::displayLabel((string) $bed, $coach, 'sharing');
            self::drawCell($im, $info, $label, $unitLocks, $coach, $x, $y, $w, $fill, $stroke, $ink, $muted, $line, $pink);
            $x += $w + self::CELL_GAP;
            $i += $span - 1;
        }
    }

    private static function drawCell($im, array $info, string $label, array $unitLocks, string $coach, int $x, int $y, int $w,
                                     array $fill, array $stroke, int $ink, int $muted, int $line, int $pink): void
    {
        $h = self::CELL_H;
        $sale = $info['sale'];
        $status = (string) $info['status'];
        $kind = $status;
        if ($status === 'booked') {
            $kind = $info['cabin'] !== null ? 'private' : ($sale !== null && !in_array($sale['status'], ['confirmed', 'completed'], true) ? 'pending' : 'booked');
        }
        self::roundRect($im, $x, $y, $x + $w, $y + $h, 10, $fill[$kind] ?? $fill['open'], $stroke[$kind] ?? $stroke['open']);

        /* women-only cabin: a pink top bar */
        $unit = Seats::unitKey((string) $info['bed'], $coach, 'sharing');
        $lock = $unitLocks[$unit] ?? '';
        if ($lock === 'female_only') {
            imagefilledrectangle($im, $x + 10, $y + 3, $x + $w - 10, $y + 7, $pink);
        }

        self::text($im, 20, $x + 12, $y + 12, $ink, $label, true);
        $tag = match ($kind) {
            'private' => 'PRIVATE',
            'pending' => 'PENDING',
            'booked'  => ($sale !== null && $sale['is_cod'] ? 'CASH' : 'PAID'),
            'held'    => 'HELD',
            'blocked' => 'BLOCKED',
            'staff'   => 'STAFF',
            default   => '',
        };
        if ($tag !== '') {
            self::text($im, 11, $x + $w - 12 - self::width(11, $tag), $y + 15, $stroke[$kind] ?? $muted, $tag, true);
        }
        if ($lock === 'female_only') {
            self::text($im, 10, $x + $w - 12 - self::width(10, 'WOMEN ONLY'), $y + 32, $pink, 'WOMEN ONLY', true);
        }

        if ($sale === null) {
            if ($status === 'blocked') {
                self::text($im, 13, $x + 12, $y + 48, $muted, 'Out of service');
            } elseif ($status === 'staff') {
                self::text($im, 13, $x + 12, $y + 48, $muted, 'Staff / emergency berth');
            } elseif ($status === 'held') {
                self::text($im, 13, $x + 12, $y + 48, $muted, 'Being booked right now');
            }
            return;
        }

        /* The name as the passenger wrote it. This used to print the literal
           words "(Nepali name)" in the berth, so the crew at the door had a
           bed they could not match to a person while the same booking's ticket
           named them correctly (audit, 11 Sep 2026). Ticket::displayOr keeps
           Devanagari and falls back to Roman, then to a dash. */
        $names = array_values(array_filter(array_map(
            static fn(string $n): string => Ticket::displayOr($n, ''),
            $sale['names']
        )));
        $nameLine = $names !== [] ? implode(', ', $names) : '-';
        if ($sale['genders'] !== []) {
            $g = array_unique(array_filter(array_map(static fn(string $s): string => strtoupper(substr($s, 0, 1)), $sale['genders'])));
            if ($g !== []) { $nameLine .= '  [' . implode('/', $g) . ']'; }
        }
        self::text($im, 16, $x + 12, $y + 40, $ink, self::fit(16, $nameLine, $w - 24), true);
        $phone = self::roman($sale['phone']);
        self::text($im, 14, $x + 12, $y + 64, $ink, $phone !== '' ? $phone : '-');
        $b = Boarding::stopDisplay($sale['board']);
        $d = Boarding::stopDisplay($sale['drop']);
        $trip = ($b['code'] !== '' ? $b['code'] : '?') . ' -> ' . ($d['code'] !== '' ? $d['code'] : '?');
        $pnr  = self::roman($sale['pnr']);
        $pw   = self::width(11, $pnr);
        self::text($im, 12, $x + 12, $y + 87, $muted, self::fit(12, $trip, $w - 24 - $pw - 8));
        self::text($im, 11, $x + $w - 12 - $pw, $y + 88, $muted, $pnr);
    }

    /* ------------------------------------------------------------------ */
    /*  Text helpers                                                       */
    /* ------------------------------------------------------------------ */

    private static function font(): string
    {
        return dirname(__DIR__) . '/assets/fonts/NotoSansDevanagari.ttf';
    }

    /** Draw text with y = TOP edge; faux-bold by a 1px double strike. */
    private static function text($im, float $size, int $x, int $y, int $col, string $text, bool $bold = false): void
    {
        if ($text === '') {
            return;
        }
        // The drawing boundary — see dev_shape() in helpers.php. Passenger
        // names reach this file in Devanagari since 11 Sep 2026, and GD does
        // not move the short-i matra in front of its consonant on its own.
        $text = dev_shape($text);
        $box = imagettfbbox($size, 0, self::font(), $text);
        $baseline = $y - (int) min($box[5], $box[7]);
        imagettftext($im, $size, 0, $x, $baseline, $col, self::font(), $text);
        if ($bold) {
            imagettftext($im, $size, 0, $x + 1, $baseline, $col, self::font(), $text);
        }
    }

    private static function width(float $size, string $text): int
    {
        if ($text === '') {
            return 0;
        }
        $box = imagettfbbox($size, 0, self::font(), dev_shape($text));
        return (int) (max($box[2], $box[4]) - min($box[0], $box[6]));
    }

    /** Cut a line to the width available, ending in ".." when it had to shrink. */
    private static function fit(float $size, string $text, int $maxW): string
    {
        if (self::width($size, $text) <= $maxW) {
            return $text;
        }
        /* mb_substr, not substr: a byte-wise cut lands inside a three-byte
           Devanagari codepoint and GD then draws NOTHING at all — the whole
           cell comes out blank rather than shortened. */
        $t = $text;
        while (mb_strlen($t) > 1 && self::width($size, $t . '..') > $maxW) {
            $t = mb_substr($t, 0, mb_strlen($t) - 1);
        }
        return rtrim($t) . '..';
    }

    private static function roundRect($im, int $x1, int $y1, int $x2, int $y2, int $r, int $fillCol, ?int $border): void
    {
        imagefilledrectangle($im, $x1 + $r, $y1, $x2 - $r, $y2, $fillCol);
        imagefilledrectangle($im, $x1, $y1 + $r, $x2, $y2 - $r, $fillCol);
        foreach ([[$x1 + $r, $y1 + $r], [$x2 - $r, $y1 + $r], [$x1 + $r, $y2 - $r], [$x2 - $r, $y2 - $r]] as [$cx, $cy]) {
            imagefilledellipse($im, $cx, $cy, $r * 2, $r * 2, $fillCol);
        }
        if ($border !== null) {
            imagerectangle($im, $x1, $y1, $x2, $y2, $border);
        }
    }

    private static function rupees(float $v): string
    {
        return 'Rs ' . number_format($v, 0);
    }

    public static function challanNo(array $sched): string
    {
        return 'CH-' . str_replace('-', '', (string) ($sched['travel_date'] ?? '')) . '-' . strtoupper((string) ($sched['route_code'] ?? ''))
             . ((int) ($sched['slot'] ?? 1) > 1 ? '-' . (int) $sched['slot'] : '');
    }

    /**
     * ASCII-only text for GD (no shaping engine): common Unicode
     * punctuation becomes its ASCII lookalike, everything else
     * (Devanagari, emoji) is dropped and an emptied "()" collapsed.
     *
     * This used to be a second, identical copy of Ticket::latin(). It is
     * now the one rule, borrowed — every PNG document in the app strips
     * text the same way, so a name cannot read one way on the ticket and
     * another on the challan (10 Sep 2026). ChallanPng::draw() already
     * calls Ticket::logoFile(), so ticket.php is loaded wherever this runs.
     */
    public static function roman(string $text): string
    {
        return Ticket::roman($text);
    }
}
